# permissions for end users to view vulnerabilityreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vulnerabilityreport-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: report-operator
    app.kubernetes.io/part-of: report-operator
    app.kubernetes.io/managed-by: kustomize
  name: vulnerabilityreport-viewer-role
rules:
- apiGroups:
  - aquasecurity.github.io
  resources:
  - vulnerabilityreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aquasecurity.github.io
  resources:
  - vulnerabilityreports/status
  verbs:
  - get
