apiVersion: aquasecurity.github.io/v1alpha1
kind: VulnerabilityReport
metadata:
  labels:
    app.kubernetes.io/name: vulnerabilityreport
    app.kubernetes.io/instance: vulnerabilityreport-sample
    app.kubernetes.io/part-of: report-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: report-operator
  name: vulnerabilityreport-sample
spec:
  # TODO(user): Add fields here
